"""Dataset manifest builder — 04_DATASET_PROTOCOL.md "Dataset Manifest".

Records provenance and shape of whatever data the pipeline actually used, so
every downstream artifact/report can reference an exact, honest dataset version.
For synthetic data the manifest is explicitly marked synthetic.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

from ..config import Config
from ..schema import ALL_RAW_FEATURES


def build_manifest(
    df_raw: pd.DataFrame,
    cfg: Config,
    *,
    generated_at: str,
    validation_summary: dict[str, Any] | None = None,
) -> dict[str, Any]:
    source = cfg["dataset"]["source"]
    is_synth = source == "synthetic"
    target = cfg.target

    missingness = {
        c: round(float(df_raw[c].isna().mean()), 4)
        for c in df_raw.columns if df_raw[c].isna().any()
    }
    target_counts = (
        {str(k): int(v) for k, v in df_raw[target].value_counts().to_dict().items()}
        if target in df_raw.columns else {}
    )

    return {
        "dataset_name": "Home Credit Default Risk",
        "source_kind": "synthetic" if is_synth else "real",
        "synthetic_warning": (
            "SYNTHETIC DATA — generated for pipeline stress testing. All metrics "
            "derived from it are synthetic and NOT real-world results."
            if is_synth else None
        ),
        "source_url": (
            "https://www.kaggle.com/competitions/home-credit-default-risk"
            if not is_synth else "generated by loan_risk.data.synthetic"
        ),
        "retrieval_or_generation_date": generated_at,
        "primary_file": (
            cfg["dataset"]["synthetic_file"] if is_synth
            else cfg["dataset"]["primary_file"]
        ),
        "license_and_usage": (
            "Kaggle Home Credit Default Risk competition rules apply to the real "
            "data; must be accepted on Kaggle. Synthetic fixture: no license, "
            "internal use only." if not is_synth else
            "Synthetic — internally generated, no external license."
        ),
        "row_count": int(len(df_raw)),
        "column_count": int(df_raw.shape[1]),
        "target_column": target,
        "target_meaning": (
            "TARGET=1: client with payment difficulties (late payment beyond the "
            "dataset-defined threshold on at least one of the first installments); "
            "TARGET=0: all other cases. Confirm against "
            "HomeCredit_columns_description.csv when using real data."
        ),
        "target_distribution": target_counts,
        "positive_rate": (
            round(target_counts.get("1", 0) / len(df_raw), 4) if len(df_raw) else None
        ),
        "feature_descriptions": [
            {"name": f.name, "kind": f.kind, "meaning": f.meaning, "unit": f.unit,
             "source": f.source}
            for f in ALL_RAW_FEATURES
        ],
        "missingness": missingness,
        "known_limitations": [
            "Serving subset uses application-level features only; supporting "
            "tables (bureau, previous_application, ...) are an offline/advanced "
            "extension and not required for a single real-time prediction.",
            "DAYS_EMPLOYED uses the documented 365243 sentinel for pensioners/"
            "unemployed; treated as missing with an indicator.",
        ] + (["Data is synthetic; distributions approximate but do not equal the "
              "real Home Credit population."] if is_synth else []),
        "validation_summary": validation_summary,
    }


def write_manifest(manifest: dict[str, Any], cfg: Config) -> Path:
    path = cfg.path("manifest")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
    return path
